### ISSUE TITLE
Some images not showing correctly

### ISSUE THREAD

**Issue by Andulien** [BrickTwo/BrickHunter#123]
Hi there,
I noticed that some images are not displayed in the BrickHunter and am not sure if this is due to the design or an issue. And if you want this reported or not.

Here are some examples:
Part: 98138pb014
BrickHunter (BH) Link: https://img.bricklink.com/ItemImage/PN/9999/98138pb014.png
BrickLink (BL) Link: https://img.bricklink.com/ItemImage/PN/150/98138pb014.png

Part: 3626cpb0001
BH Link: https://img.bricklink.com/ItemImage/PN/9999/3626cpb0001.png
BL: Link: https://img.bricklink.com/ItemImage/PN/1/3626cpb0001.png

Part: 98138pb033
BH Link: https://img.bricklink.com/ItemImage/PN/9999/98138pb033.png
BL Link: https://img.bricklink.com/ItemImage/PN/95/98138pb033.png

Part: coltlnm20
BH Link: https://img.bricklink.com/ItemImage/MN/9999/coltlnm20.png
BL Link: https://img.bricklink.com/ItemImage/MN/0/coltlnm20.png

Keep up the great work. Thank you.

**Comment by BrickTwo** [comment]
Hi Andulien,
Thx for your feedback. The reason why BrickHunter isn't shown a image for your examples is because you didn't have defined a color for those bricks in your wantedList at BrickLink. i.e. for 98138pb014 you would have to define Medium Nougat. I will consider this for BrickHunter 2.0 which is currently in development.

**Comment by Andulien** [comment]
Hi,
I didn't know. I just tested it with the first three items and it worked. If I add a color in Bricklink and then import again the images are shown. Would be neat if you could change the color within BH.

What about the last item which is actually a Minifigure? There I can't set a color in Bricklink.

Thank you for the quick reply :)

**Comment by BrickTwo** [comment]
Minifigs or other "combined" parts (i.e. windows) have to be  "part out" otherwise BrickHunter can't find prices/availability for special parts at LEGO. I have to check if I can detect these positions and add a option for part them out inside BrickHunter.

**Comment by Andulien** [comment]
Understood. Thanks for clarifying. Feel free to close or add it to your feature requests :)
