### ISSUE TITLE
Loading Prices gets stuck when certain parts are in the list

### ISSUE THREAD

**Issue by Andulien** [BrickTwo/BrickHunter#124]
So I noticed that when I have specific parts in the list, the loading price task gets stuck. 
The only way to resolve this is cancel the task.
The part list is then marked yellow which still works with the shopping basket then.

Maybe a fix would be a timeout for those items that get stuck?

Example part is: coltlnm20

**Comment by BrickTwo** [comment]
Thx, will check if I can fix this somehow.

**Comment by BrickTwo** [comment]
Fixed with BrickHunter 2.0
