### ISSUE TITLE
Check unique item limit on Export to Lego

### ISSUE THREAD

**Issue by Andulien** [BrickTwo/BrickHunter#130]
Hello,

so I've just created several partlists in BH and wanted to add them then to Lego via the add to basket feature. However I've then noticed BH did not add all items.
It seems BH tries to add all items not knowing the unique item limit of lego. It does not tell you that you breached the limit and which items were not added, so I ended up starting to manually add the items now.  It would be great if you can add a warning or stop the upload once the limit is reached and markt he ones not yet added so you can add them once the first order is out, or split your order into two halves or something like this.

Would be great if this can be a feature for the future.

Thank you.

**Comment by BrickTwo** [comment]
Yeah I know, there is currently this ugly error once the user tries to add more than 95/97 (depends on the country) lots in the pab shopping cart. I hope Lego fixes this error soon. Anyway, I already playing around with adding a shopping cart split function for a while, and I definitely want to add it after BrickHunter 2.0 is published.

**Comment by BrickTwo** [comment]
Fixed in BrickHunter 2.0
