### ISSUE TITLE
Items are not put in the shopping cart anymore

### ISSUE THREAD

**Issue by Geekgasm** [BrickTwo/BrickHunter#178]
Currently, with Brickhunter version 1.8.0 the items cannot be added to the shopping cart anymore.

System: 
* MacBook Air (M1, 2020)
* macOS Monterey 12.3

Browser: Google Chrome Version 100.0.4896.60 (Offizieller Build) (arm64)

In Chrome, the progress bar is progressing to the end, the popup appears that the items have been placed in the shopping cart, but afterwards the Pick-A-Brick shopping cart on the LEGO shop@home site is still empty.

Browser: Firefox 98.0.2 (64-Bit)

In Firefox the parts list in Brickhunter turns grey and the progress bar is stuck at 0%.

Both LEGO shop@home and Brickhunter are set to Germany/German

**Comment by BrickTwo** [comment]
fixed with v1.8.1

**Comment by Geekgasm** [comment]
Wow! That was fast! Thank you so much!
