### ISSUE TITLE
Request - Option to add only Bestseller to PAB

### ISSUE THREAD

**Issue by Andulien** [BrickTwo/BrickHunter#183]
Just like with setting a min price point when adding to Pick a Brick vs. Bricklink it would be great to also choose to only add Bestseller items to Pick a Brick as the Standard Items take up to 6 weeks or more to deliver and sometime one might want to order those items via Bricklink as that will be faster.

Thanks and keep up the great support.

**Comment by BrickTwo** [comment]
Good idea, I'll check if I can add this easily with the current version

**Comment by BrickTwo** [comment]
implemented in BrickHunter 2.0
