### ISSUE TITLE
Wrong Mapping of items

### ISSUE THREAD

**Issue by henriquedesousa** [BrickTwo/BrickHunter#184]
Hello. I've started using BrickHunter today and I don't why, but the following part:

> 970c00 |   | Dark Brown[Dark Brown]

Is being mapped on LEGO shopping cart as:

> FLAT TILE 2X4, NO. 240
> ID: 6329620/74040

Here's a bricklink XML to easily reproduce the bug:

```
<INVENTORY>
 <ITEM>
  <ITEMID>970c00</ITEMID>
  <ITEMTYPE>P</ITEMTYPE>
  <COLOR>120</COLOR>
  <CATEGORY>484</CATEGORY>
  <QTY>1</QTY>
  <PRICE>0.000</PRICE>
  <CONDITION>N</CONDITION>
 </ITEM>
</INVENTORY>
```

Many thanks in advance.

**Comment by BrickTwo** [comment]
Interessting, so BrickHunter is showing you the part 6329620/74040 in the List? I tested it with your provided XMl and it links correctly to 73200/4529672 which is then also added to the shopping cart at lego.com

![image](https://user-images.githubusercontent.com/61464373/188579298-d853cfd2-19d9-4651-abc5-6cf007020524.png)

**Comment by henriquedesousa** [comment]
Yes, I just reproduced it again and still the same issue occurs. I've also tried changing the language in the settings and use the same language settings on LEGO website to germany/German, (de-de), but the same issue occurs :)  I'm using the german version of Chrome, called SRWare Iron Version 102.0.5200.0 (Official Build) (64-bit)

**Comment by henriquedesousa** [comment]
Just updated to SRWare Iron Version 103.0.5250.0 (Official Build) (64-bit), still the same. Please check the following video :)

https://www.veed.io/view/25d78032-2212-427a-9aef-4ad1b9d4d489
