### ISSUE TITLE
Shopping Cart does not add Standard pieces to Lego Cart

### ISSUE THREAD

**Issue by stan2544** [BrickTwo/BrickHunter#188]
Creating a list then having the cart be populated on BH then sending the cart to Lego.com loses the pieces that are labeled Standard. 

### On BH: 
Parts List
273->272 (1245)
Pick a Brick: 247 (1180)
BrickLink: 25 (65)
Not allocated: 0 (0)
Total at LEGO: 247
### Price
Pick a Brick: USD 113.24
BrickLink: 0
Total: USD 113.24

### After being sent to Lego: 
Subtotal: $38.41
Bestseller: $38.41
Standard: $0.00

**Comment by BrickTwo** [comment]
I just tested it and it worked as expected. Which Brickhunter version and Browser are you using?

**Comment by stan2544** [comment]
Latest version 1.9.9 and Firefox. Testing it on Chrome showed expected behavior.
________________________________

**Comment by BrickTwo** [comment]
I will test again on Firefox once it's possible again to order Standard pieces somewhen in January

**Comment by BrickTwo** [comment]
Fixed with BrickHunter 2.0
