### ISSUE TITLE
Sending to Lego doesn't work anymore?

### ISSUE THREAD

**Issue by cipidos** [BrickTwo/BrickHunter#189]
The standard items are working back at Lego :-). But they also changed something to their site. Now it seems that Brickhunter doesn't sent the list anymore to Lego. It said that Lego isn't open (it was open in the previous tab on the left) and asks if it can open the Lego site. It opens a new tab and the Lego site, but no bricks are added to the PAB.

I'm using chrome on a mac with BH version 1.9.9

**Comment by BrickTwo** [comment]
That can happen from time to time. Try to close all open tabs and restart again.

**Comment by cipidos** [comment]
Txs Will try that next time as I have ordered in the meantime.

**Comment by BrickTwo** [comment]
issue closed
