### ISSUE TITLE
Color information missing in Single parts list

### ISSUE THREAD

**Issue by Geekgasm** [BrickTwo/BrickHunter#193]
## Soft- and Hardware Information
* Brickhunter version: 1.9.11
* Browser: 
  * Google Chrome Version 111.0.5563.146 (Offizieller Build) (arm64)
  * Firefox 111.0.1 (64-Bit)
* OS: macoS Ventura Version 13.2.1
* MacBook Air Apple M1

## Issue
* When picking elements from the single parts selector, the items show up in the _Single part list_ with color _Not defined!_.
* When importing the same parts from a Bricklink XML file into a new parts list the color is shown correctly.
* Note: when filling the PAB shopping cart the colors are correctly transferred. This seems to be a display problem only.

## Steps to reproduce

1. In the single parts selector, select some parts (colors are shown here correctly). E.g. design 79389:
<img width="748" alt="Bildschirm­foto 2023-03-28 um 21 32 20" src="https://user-images.githubusercontent.com/12259134/228351530-317e388e-29d2-4d23-ab7b-9a9ede1b3c1e.png">

2. Open the single parts list: the color is not shown:
<img width="1194" alt="Bildschirm­foto 2023-03-28 um 21 35 35" src="https://user-images.githubusercontent.com/12259134/228351822-f41ac21d-a7c7-4988-8cfc-cbe66c6a819f.png">

3. Import a new list from XML file: 
```
<INVENTORY>
	<ITEM>
		<ITEMTYPE>P</ITEMTYPE>
		<ITEMID>79389</ITEMID>
		<COLOR>86</COLOR>
		<MINQTY>1</MINQTY>
	</ITEM>
	<ITEM>
		<ITEMTYPE>P</ITEMTYPE>
		<ITEMID>79389</ITEMID>
		<COLOR>2</COLOR>
		<MINQTY>1</MINQTY>
	</ITEM>
	<ITEM>
		<ITEMTYPE>P</ITEMTYPE>
		<ITEMID>79389</ITEMID>
		<COLOR>11</COLOR>
		<MINQTY>1</MINQTY>
	</ITEM>
</INVENTORY>
```

4. Open the new list from the import: the colors are shown correctly:
<img width="1195" alt="Bildschirm­foto 2023-03-28 um 21 36 18" src="https://user-images.githubusercontent.com/12259134/228352487-1420f8b3-a2fe-4de9-b6a8-5a7c2772ba4b.png">

**Comment by BrickTwo** [comment]
Fixed with BrickHunter 2.0
