### ISSUE TITLE
Not adding to cart on Lego USA website

### ISSUE THREAD

**Issue by Jibble1** [BrickTwo/BrickHunter#194]
I upload an xml, click download prices, then go to shopping cart and click "Pick a Brick" then "Add to shopping cart". It shows the progress bar and says "Shopping cart successfully filled". However, on the Lego.com tab, all it actually does it takes me to the Lego Pick a Brick page, and my cart is empty. This is true in Chrome, Firefox and Edge, and was true for all three xml files I tried, with as few as 89 bricks. Appreciate your help!

**Comment by BrickTwo** [comment]
Yeah, there is currently an error on the LEGO PaB service if you add more than 20 Standard/Bestseller lots. Lego devs are informed.

**Comment by Jibble1** [comment]
> Yeah, there is currently an error on the LEGO PaB service if you add more than 20 Standard/Bestseller lots. Lego devs are informed.

Thanks a lot for the quick reply, that's very helpful to know. I'll just parse it into blocks of less than 20 for now.
