### ISSUE TITLE
Export to Bricklink XML is broken

### ISSUE THREAD

**Issue by popovitsj** [BrickTwo/BrickHunter#199]
When exporting to bricklink XML, I get an XML file like:

```
<INVENTORY>
  <ITEM>
    <ITEMTYPE>P</ITEMTYPE>
    <ITEMID>2564</ITEMID>
    <COLOR>11</COLOR>
    <MAXPRICE/>
    <MINQTY>1</MINQTY>
    <QTYFILLED/>
    <CONDITION/>
    <NOTIFY/>
    <REMARKS/>
  </ITEM>
</INVENTORY>
```

When trying to import this into bricklink, I get the following error: `Invalid File Format: null`

The issue is caused by the empty tags like `<QTYFILLED/>`. After removing all the empty tags, it works:

```
<INVENTORY>
  <ITEM>
    <ITEMTYPE>P</ITEMTYPE>
    <ITEMID>2564</ITEMID>
    <COLOR>11</COLOR>
    <MINQTY>1</MINQTY>
  </ITEM>
</INVENTORY>
```

**Comment by popovitsj** [comment]
A workaround that I found is first uploading the generated XML to rebrickable, then exporting it to Bricklink XML.

**Comment by Geekgasm** [comment]
I would actually see this more as a bug in Bricklink, but of course it's a nuisance to have to reformat the XML to make it work with Bricklink.
Another way to get rid of the empty tags is to run the XML through my little command-line tool "brickdiff". While it was designed to add, subtract brick lists and calculate intersection or union, it can also be used to just read an XML file, parse it and output it again. For your example you will get this:

```
> cat foo.xml            
<INVENTORY>
  <ITEM>
    <ITEMTYPE>P</ITEMTYPE>
    <ITEMID>2564</ITEMID>
    <COLOR>11</COLOR>
    <MAXPRICE/>
    <MINQTY>1</MINQTY>
    <QTYFILLED/>
    <CONDITION/>
    <NOTIFY/>
    <REMARKS/>
  </ITEM>
</INVENTORY>

> brickdiff id foo.xml -m -s
<?xml version="1.0" encoding="UTF-8"?>
<INVENTORY>
  <ITEM>
    <ITEMTYPE>P</ITEMTYPE>
    <ITEMID>2564</ITEMID>
    <COLOR>11</COLOR>
    <MINQTY>1</MINQTY>
  </ITEM>
</INVENTORY>
```

You can find brickdiff here: https://github.com/Geekgasm/brickdiff

**Comment by popovitsj** [comment]
I agree that semantically, it's incorrect that Bricklink rejects empty XML tags. I'll also create a bug report on bricklink side.

**Comment by BrickTwo** [comment]
Actually you can just remove the first line (the xml definition line) and then it should be possible to import even with empty XML tags. You can't even directly import a wanted list which is exported from BrickLink :). But I agree that BrickHunter should export in a format which is possible to directly import into BrickLink than the format BrickLink is using for the export

**Comment by Geekgasm** [comment]
> Actually you can just remove the first line (the xml definition line) and then it should be possible to import even with empty XML tags.

Not sure what you mean by that. Bricklink doesn't seem to care whether the xml definition line is there. Import works just fine with or without it, but the empty tags lead to an error during import either way.

**Comment by Geekgasm** [comment]
> Thanks for the tip, it seems like that tool would be a better workaround for now than having to go through rebrickable.

By the way, by default brickdiff does not output to the console, but puts the output in the clipboard. That way, if you want to upload to Bricklink you don't need to open the xml file to copy the content from the editor. 

I never understood why Bricklink does not allow to upload a Bricklink XML file from the computer like for other file formats, but requires you to paste the XML into an edit field to create a wanted list from it...

**Comment by BrickTwo** [comment]
> Are you referring to the import via selecting a file from the computer? I find it really strange that they don't support that. But going via the copy/paste in the "Upload BrickLink XML format" tab, the XML format that is exported from Bricklink can be imported again without error. I just tried it out.

maybe they changed it recently. it wasn't possible in the past unless I removed the xml definition line. have to check it out later.

**Comment by Geekgasm** [comment]
> maybe they changed it recently. it wasn't possible in the past unless I removed the xml definition line. have to check it out later.

When I implemented the export for my brickdiff tool I added this, because it was also included in the export output from Bricklink. It never gave me trouble when trying to upload the output from my tool. But I also noticed that the xml line is not included in an export from Bricklink Studio (File -> Export as WL xml...").

I thought it's more proper to have the line, but maybe I should remove it... I did some extra lines of code to add it, haha!

**Comment by BrickTwo** [comment]
BrickLink have indeed changed the upload a bit. The problem was no longer the file definition line but empty tags which should have a number format. It's fine to have empty condition and remarks tags.
The bugfix will be delivered together with the next feature release in the coming days.
Thanks for reporting.

**Comment by popovitsj** [comment]
Thanks. Awesome tool btw, I find Lego's Pick a Brick to be all but unusable without it.
