### ISSUE TITLE
Unable to transfer to LEGO website / Uncaught promise

### ISSUE THREAD

**Issue by henriquedesousa** [BrickTwo/BrickHunter#204]
BrickHunter 2.0, latest Chrome Version 119.0.6045.106 (Official Build) (64-bit)

No messages in the Console tab of DevTools.

Notice how Pieces and Price appear as NaN. Country and language configured as such also on Lego website.

![image](https://github.com/BrickTwo/BrickHunter/assets/12630569/fcc605c7-6f9d-465a-b804-f922605ab09e)

I also got another bug when importing the XML file mentioned in https://github.com/BrickTwo/BrickHunter/issues/184 

![image](https://github.com/BrickTwo/BrickHunter/assets/12630569/61356716-3160-438a-9199-57f8e7748050)

Thanks in advance.

**Comment by BrickTwo** [comment]
HI,

Can you provide me your wantedList where you get the NaN error? Attach it here or send it to info@bricktwo.net, thx.

The second error is something else. it's currently not possible to import just one part, as soon as you add a second part (i.e. same part but different color), it's working. it's a know bug, but with low priority (who is just importing one part? :) ).

**Comment by henriquedesousa** [comment]
Done. Btw, website is https://www.lego.com/en-pt and settings are 
![image](https://github.com/BrickTwo/BrickHunter/assets/12630569/d8ef6e38-3a48-45b4-9101-1e69a1ca2a84)

**Comment by BrickTwo** [comment]
Looks like the quantity is somehow not imported. Will try to fix it this weekend. As a workaround you can just assign a quantity for each position of the Parts List, after that, everything should work.

**Comment by mevitsbricks** [comment]
I believe I am seeing the same issue.  I have quantities in my XML that weren't imported to BH.  You mentioned assigning quantities for each position, is that something I can do via BH?

**Comment by mevitsbricks** [comment]
I had created the XML file I used to upload to BH via Brickstore.   The brickstore xml export imported to BH without qty.   I then tested uploading from brickstore to bricklink wanted list, then downloaded that wanted list from bricklink, and then imported it to BH which worked fine.  The qty showed up.   Just wondering how @henriquedesousa might have created the XML file.

**Comment by henriquedesousa** [comment]
I exported in BrickStore via "BrickLink XML" Ctrl+E, Ctrl+X

**Comment by mevitsbricks** [comment]
So both were done the same way.  So something about the XML from brickstore
and BL wanted lists are different.

**Comment by BrickTwo** [comment]
Sorry for my late reply, I where in vacation far away in the last weeks :)

Seems like BrickStore is not using the same name for the Quantity (QTY instead on MINQTY) and Price (PRICE instead of MAXPRICE) information. That's why BrickHunter is not importing these information. Will try to support it in BrickHunter by this Weekend and publish it together with some Bug fixes.

![image](https://github.com/BrickTwo/BrickHunter/assets/61464373/708225c3-289b-4e1d-b1bc-6ea0bcc6ed1f)

**Comment by BrickTwo** [comment]
Fixed with Version 2.2.8

**Comment by mevitsbricks** [comment]
Thank you very much!

Kevin (Mevit)
www.mevitsbricks.com
Brick by Brick By Brick!!!
